# Generated by Django 6.0.2 on 2026-02-14 19:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Journée')),
                ('phase', models.CharField(choices=[('aller', 'Phase Aller'), ('retour', 'Phase Retour')], default='aller', max_length=10, verbose_name='Phase')),
                ('date_played', models.DateTimeField(blank=True, null=True, verbose_name='Date du match')),
                ('is_played', models.BooleanField(default=False, verbose_name='Match joué')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matchs',
                'ordering': ['phase', 'matchday', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'équipe")),
                ('player_name', models.CharField(max_length=100, verbose_name='Nom du joueur')),
                ('gamer_pseudo', models.CharField(max_length=100, verbose_name='Pseudo gamer')),
                ('contact', models.CharField(blank=True, max_length=20, verbose_name='Contact (téléphone)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name="Logo de l'équipe")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Équipe',
                'verbose_name_plural': 'Équipes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Doit changer le mot de passe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Admin',
                'verbose_name_plural': 'Profils Admin',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Score domicile')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Score extérieur')),
                ('validated', models.BooleanField(default=False, verbose_name='Validé par admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='league.match', verbose_name='Match')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0, verbose_name='Matchs joués')),
                ('won', models.PositiveIntegerField(default=0, verbose_name='Victoires')),
                ('drawn', models.PositiveIntegerField(default=0, verbose_name='Nuls')),
                ('lost', models.PositiveIntegerField(default=0, verbose_name='Défaites')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='Buts marqués')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='Buts encaissés')),
                ('goal_difference', models.IntegerField(default=0, verbose_name='Différence de buts')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Points')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standing', to='league.team', verbose_name='Équipe')),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'ordering': ['-points', '-goal_difference', '-goals_for'],
            },
        ),
        migrations.CreateModel(
            name='PlayoffMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('semi_1_leg1', 'Demi-finale 1 - Aller'), ('semi_1_leg2', 'Demi-finale 1 - Retour'), ('semi_2_leg1', 'Demi-finale 2 - Aller'), ('semi_2_leg2', 'Demi-finale 2 - Retour'), ('third_place', 'Match 3ème place'), ('final', 'Finale')], max_length=20, verbose_name='Tour')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Score domicile')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Score extérieur')),
                ('is_played', models.BooleanField(default=False, verbose_name='Match joué')),
                ('has_extra_time', models.BooleanField(default=False, verbose_name='Prolongations')),
                ('has_penalties', models.BooleanField(default=False, verbose_name='Tirs au but')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoff_away', to='league.team', verbose_name='Équipe extérieur')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoff_home', to='league.team', verbose_name='Équipe domicile')),
                ('penalty_winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_wins', to='league.team', verbose_name='Vainqueur aux tirs au but')),
            ],
            options={
                'verbose_name': 'Match Phase Finale',
                'verbose_name_plural': 'Matchs Phase Finale',
                'ordering': ['round_type'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.team', verbose_name='Équipe extérieur'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.team', verbose_name='Équipe domicile'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('home_team', 'away_team', 'phase')},
        ),
    ]
